name: Tiny workflow

on:
  push:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create project card
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh --version
#          gh api graphql -f query='
#            mutation {
#              addProjectV2ItemById(input: {projectId: "PVT_kwHOAXzAhM4Ab_pK" contentId: "5"}) {
#                item {
#                  id
#                }
#              }
#            }'
          gh api graphql -f query='
            mutation createIssue {
              createIssue(input:{
                title: "Create issue from GraphQL",
                repositoryId :"R_kgDOKy8yng", 
                projectIds:"PVT_kwHOAXzAhM4Ab_pK"
              }) {
                issue {
                  id
                }
              }
            }'
