name: Publish Drafts

on:
#  schedule:
#    - cron: '0 0 * * *' # 毎日0時に実行
#  workflow_dispatch:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # 必要に応じてRubyのバージョンを指定

      - name: Run Ruby script
        id: run_script
        run: |
          ruby script/publish_drafts.rb >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.run_script.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          branch=${{ steps.run_script.outputs.branch_name }}
          echo '==== checkout ===='
          git checkout -b $branch
          git add *.md
          git commit -m 'Publish drafts'
          echo '==== push ===='
          git push origin $branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: steps.run_script.outputs.changes == 'true'
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "${{ steps.run_script.outputs.branch_name }}"
          title: 'Publish drafts'
          base: 'main'
          body: 'This PR publishes drafts.'

#      - name: Send Slack notification
#        if: steps.run_script.outputs.changes == 'true'
#        uses: 8398a7/action-slack@v3
#        with:
#          status: custom
#          fields: repo,message,commit,author
#          custom_payload: |
#            {
#              "text": "レビューお願いします: ${{ steps.create_pr.outputs.pull-request-url }}"
#            }
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
